### ISSUE TITLE
Doesnt work on 1.21.5

### ISSUE THREAD

**Issue by FemBoysAreCut3** [marlester-dev/ReallyFakePlayers#53]
[12:17:09] [Server thread/ERROR]: Error occurred while enabling RFP v4.1.4 (Is it up to date?)
java.lang.NoClassDefFoundError: org/geysermc/mcprotocollib/network/tcp/TcpClientSession
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at io.papermc.paper.plugin.entrypoint.classloader.BytecodeModifyingURLClassLoader.defineClass(BytecodeModifyingURLClassLoader.java:113) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at io.papermc.paper.plugin.entrypoint.classloader.BytecodeModifyingURLClassLoader.findClass(BytecodeModifyingURLClassLoader.java:67) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:129) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3473) ~[?:?]
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2542) ~[?:?]
	at com.google.inject.internal.DeclaredMembers.getDeclaredFields(DeclaredMembers.java:40) ~[?:?]
	at com.google.inject.spi.InjectionPoint.getDeclaredFields(InjectionPoint.java:809) ~[?:?]
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:719) ~[?:?]
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:432) ~[?:?]
	at com.google.inject.assistedinject.FactoryProvider2.getDependencies(FactoryProvider2.java:684) ~[?:?]
	at com.google.inject.assistedinject.FactoryProvider2.<init>(FactoryProvider2.java:344) ~[?:?]
	at com.google.inject.assistedinject.FactoryModuleBuilder$1.configure(FactoryModuleBuilder.java:336) ~[?:?]
	at com.google.inject.AbstractModule.configure(AbstractModule.java:64) ~[?:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:426) ~[?:?]
	at com.google.inject.AbstractModule.install(AbstractModule.java:106) ~[?:?]
	at ReallyFakePlayers.jar/me.marlester.rfp.fakeplayers.FakePlayersModule.configure(FakePlayersModule.java:30) ~[ReallyFakePlayers.jar:?]
	at com.google.inject.AbstractModule.configure(AbstractModule.java:64) ~[?:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:426) ~[?:?]
	at com.google.inject.spi.Elements.getElements(Elements.java:113) ~[?:?]
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160) ~[?:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[?:?]
	at com.google.inject.Guice.createInjector(Guice.java:87) ~[?:?]
	at com.google.inject.Guice.createInjector(Guice.java:69) ~[?:?]
	at com.google.inject.Guice.createInjector(Guice.java:59) ~[?:?]
	at ReallyFakePlayers.jar/me.marlester.rfp.ReallyFakePlayers.onEnable(ReallyFakePlayers.java:67) ~[ReallyFakePlayers.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:648) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:741) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:486) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1161) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:308) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.geysermc.mcprotocollib.network.tcp.TcpClientSession
	at io.papermc.paper.plugin.entrypoint.classloader.BytecodeModifyingURLClassLoader.findClass(BytecodeModifyingURLClassLoader.java:75) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 45 more
[12:17:09] [Server thread/INFO]: [RFP] Disabling RFP v4.1.4
[12:17:09] [Server thread/ERROR]: Error occurred while disabling RFP v4.1.4
java.lang.NullPointerException: Cannot invoke "com.google.inject.Injector.getInstance(java.lang.Class)" because "this.injector" is null
	at ReallyFakePlayers.jar/me.marlester.rfp.ReallyFakePlayers.onDisable(ReallyFakePlayers.java:95) ~[ReallyFakePlayers.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:286) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:648) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:741) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:486) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1161) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:308) ~[paper-1.21.5.jar:1.21.5-42-02d20ff]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by connor33341** [comment]
lmao, you are using 1.21.5, It appears that some dependencies need to be updated in order to support this new version. And some code on RFP needs to be changed to support the new dependencies. Right now, the issue is with geysermc/protocallib which has changed with the latest version

**Comment by FemBoysAreCut3** [comment]
Im using the latest dev build of everything, just tell me when your plugin is fixxed then ill use it
